# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
sudo: false
warnings_are_errors: true

services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libpq-dev

env:
  global:
  - NOT_CRAN: true
  - MAKEFLAGS="-j8"

matrix:
  include:
  - os: osx
  - os: linux
    r: devel
  - os: linux
    r: release
    env:
    - R_CODECOV: true
  - os: linux
    r: oldrel
  - os: linux
    r: 3.2


r_packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm -rf /usr/local/var/postgres; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s travis || true; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createdb travis || true; fi

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
