# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

services:
  - postgresql
addons:
  postgresql: "9.4"

apt_packages:
  - libpq-dev

r_github_packages:
  - rstats-db/DBI
  - jimhester/covr
  - rstats-db/DBItest@production

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
