language: r
sudo: required
warnings_are_errors: true

apt_packages:
  - libpq-dev

r_github_packages:
  - RcppCore/Rcpp
  - rstats-db/DBI
  - jimhester/covr

before_script:
  - psql -c 'create database travis;' -U postgres

after_success:
  - Rscript -e 'covr::codecov()"
