language: r

apt_packages:
  - libpq-dev

r_github_packages:
  - rstats-db/DBI
  - jimhester/covr
  - rstats-db/DBItest@production

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  postgresql: "9.4"
